name: content_scripter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  uuid: ^4.4.0
  intl: ^0.20.1
  shimmer: ^3.0.0
  timezone: ^0.10.0
  fl_chart: ^1.0.0
  share_plus: ^11.0.0
  flutter_tts: ^4.0.2
  image_picker: ^1.0.7
  fluttertoast: ^8.2.4
  flutter_bloc: ^9.1.1
  intro_slider: ^4.2.1
  url_launcher: ^6.2.4
  speech_to_text: ^7.0.0
  cupertino_icons: ^1.0.6
  country_picker: ^2.0.24
  flutter_markdown: ^0.7.5
  connectivity_plus: ^6.1.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  google_generative_ai: ^0.4.0
  flutter_staggered_animations: ^1.1.1
  flutter_widget_from_html: ^0.16.0
  dotted_border: ^3.0.1
  barcode_widget: ^2.0.4
  screenshot: ^3.0.0
  path_provider: ^2.1.3
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  icons_launcher: ^3.0.0
  rename: ^3.0.1

icons_launcher:
  image_path: "assets/images/applogo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/bold.ttf
    - family: SemiBold
      fonts:
        - asset: assets/fonts/semibold.ttf
    - family: Medium
      fonts:
        - asset: assets/fonts/medium.ttf
    - family: Regular
      fonts:
        - asset: assets/fonts/regular.ttf
    - family: ExtraBold
      fonts:
        - asset: assets/fonts/extrabold.ttf
